# Generated by Django 4.2 on 2023-04-25 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectcontributor",
            old_name="contributor",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="projectcontributor",
            unique_together={("project", "user")},
        ),
    ]
