# Generated by Django 4.2 on 2023-04-25 22:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0002_rename_contributor_projectcontributor_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectContributor",
            new_name="Contributor",
        ),
        migrations.RemoveField(
            model_name="project",
            name="contributors",
        ),
    ]
