# Generated by Django 4.2 on 2023-04-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0008_rename_project_comment_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Owner"), ("CONTRIBUTOR", "Contributor")],
                default="CONTRIBUTOR",
                max_length=30,
            ),
        ),
    ]
