# Generated by Django 4.2 on 2023-05-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0012_alter_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="project",
            field=models.ForeignKey(
                default=36,
                on_delete=django.db.models.deletion.CASCADE,
                to="issues.project",
            ),
            preserve_default=False,
        ),
    ]
