# Generated by Django 4.2 on 2023-05-08 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0013_comment_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="project",
        ),
    ]
