# Generated by Django 4.2 on 2023-05-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0014_remove_comment_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("BE", "Back-End"),
                    ("FE", "Front-End"),
                    ("IO", "iOS"),
                    ("AN", "Android"),
                ],
                max_length=2,
            ),
        ),
    ]
